version: '3'

services:
  appointments-db:
    container_name: appointments_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=appointments

  prueba-altem:
    container_name: prueba-altem
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URL=${MONGODB_URL}
